# Generated by Django 3.0.6 on 2023-11-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pttdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField()),
                ('author', models.TextField()),
                ('title', models.TextField()),
                ('href', models.TextField()),
                ('pushcount', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
    ]
